In [7]:
import numpy as np
from scipy import linalg as la
import cvxpy as cp

# Data Generation:

In [445]:
#dataset1
miu_coef = 10
cov1_coef = 10
cov2_coef = 10
miu1 = miu_coef*np.random.random(2)
# cov1 = 100*np.identity(2)
temp1 = np.random.random((2,2))
cov1 = cov1_coef*temp1.dot(temp1.T)
data1 = np.random.multivariate_normal(miu1, cov1, 150)

#dataset2
miu2 = miu_coef*np.random.random(2)
# cov2 = 100*np.identity(2)
temp2 = np.random.random((2,2))
cov2 = cov2_coef*temp2.dot(temp2.T)
data2 = np.random.multivariate_normal(miu2, cov2, 150)

In [446]:
np.set_printoptions(precision=3)

print(f'Dataset 1:\n   mean: {miu1}\n   covariance: \n{cov1}\n\n\n\
Dataset 2:\n   mean: {miu2}\n   covariance: \n{cov2}')

Dataset 1:
   mean: [8.48  2.646]
   covariance: 
[[ 7.567  5.387]
 [ 5.387 10.206]]


Dataset 2:
   mean: [8.38  0.649]
   covariance: 
[[2.605 3.338]
 [3.338 4.297]]


# Optimization Problem:

In [447]:
X, Y, Z = data1, data2, data1 - data2
d = np.sqrt(np.sum(Z**2,axis = 1))
n = 2
# Z = X - Y
P = cvx.Variable((n,n), PSD=True)
f = 0
N = 150
for i in range(N):
    f += d[i]**2
    f += -2*d[i]*cvx.sqrt(cvx.quad_form(Z[i,:],P))
    f += cvx.quad_form(Z[i,:],P)
prob = cvx.Problem(cvx.Minimize(f/N),[P == P.T])
train_error = prob.solve()
print(f'{train_error:.8f}')


0.00000014


In [449]:
print(f'P matrix:\n{P.value}\n\nlatest error:\n{train_error:.8f}\n\ncovariance coefficient of dataset 2:\n{cov2_coef}')

P matrix:
[[1. 0.]
 [0. 1.]]

latest error:
0.00000014

covariance coefficient of dataset 2:
10


# Relation Evaluation:

In [480]:
coef = 1
temp1 = cov1*coef/10
temp2 = cov1*coef/10

In [481]:
data1 = np.random.multivariate_normal(miu1, temp1, 150)
data2 = np.random.multivariate_normal(miu2, temp2, 150)

In [482]:
X, Y, Z = data1, data2, data1 - data2
d = np.sqrt(np.sum(Z**2,axis = 1))
n = 2
# Z = X - Y
P = cvx.Variable((n,n), PSD=True)
f = 0
N = 150
for i in range(N):
    f += d[i]**2
    f += -2*d[i]*cvx.sqrt(cvx.quad_form(Z[i,:],P))
    f += cvx.quad_form(Z[i,:],P)
prob = cvx.Problem(cvx.Minimize(f/N),[P == P.T])
train_error = prob.solve()
print(f'{train_error:.8f}')


print(f'P matrix:\n{P.value}\n\nlatest error:\n{train_error:.8f}\n\ncovariance coefficient of datasets:\n{coef/10}')

0.00000006
P matrix:
[[ 1. -0.]
 [-0.  1.]]

latest error:
0.00000006

covariance coefficient of datasets:
0.1


In [477]:
coef = 100
temp1 = cov1*coef/10
temp2 = cov1*coef/10

In [478]:
data1 = np.random.multivariate_normal(miu1, temp1, 150)
data2 = np.random.multivariate_normal(miu2, temp2, 150)

In [479]:
X, Y, Z = data1, data2, data1 - data2
d = np.sqrt(np.sum(Z**2,axis = 1))
n = 2
# Z = X - Y
P = cvx.Variable((n,n), PSD=True)
f = 0
N = 150
for i in range(N):
    f += d[i]**2
    f += -2*d[i]*cvx.sqrt(cvx.quad_form(Z[i,:],P))
    f += cvx.quad_form(Z[i,:],P)
prob = cvx.Problem(cvx.Minimize(f/N),[P == P.T])
train_error = prob.solve()
print(f'{train_error:.8f}')


print(f'P matrix:\n{P.value}\n\nlatest error:\n{train_error:.8f}\n\ncovariance coefficient of datasets:\n{coef/10}')

1.09888963
P matrix:
[[0.892 0.205]
 [0.205 0.883]]

latest error:
1.09888963

covariance coefficient of datasets:
10.0


In [472]:
coef = 1000
temp1 = cov1*coef/10
temp2 = cov1*coef/10

In [473]:
data1 = np.random.multivariate_normal(miu1, temp1, 150)
data2 = np.random.multivariate_normal(miu2, temp2, 150)

In [475]:
X, Y, Z = data1, data2, data1 - data2
d = np.sqrt(np.sum(Z**2,axis = 1))
n = 2
# Z = X - Y
P = cvx.Variable((n,n), PSD=True)
f = 0
N = 150
for i in range(N):
    f += d[i]**2
    f += -2*d[i]*cvx.sqrt(cvx.quad_form(Z[i,:],P))
    f += cvx.quad_form(Z[i,:],P)
prob = cvx.Problem(cvx.Minimize(f/N),[P == P.T])
train_error = prob.solve()
print(f'{train_error:.8f}')


print(f'P matrix:\n{P.value}\n\nlatest error:\n{train_error:.8f}\n\ncovariance coefficient of datasets:\n{coef/10}')

259.98231796
P matrix:
[[0.418 0.191]
 [0.191 0.49 ]]

latest error:
259.98231796

covariance coefficient of datasets:
100.0
